# Dockerfile.api_gateway
FROM python:3.9-slim

WORKDIR /app

COPY . /app

RUN pip install Flask pika flask_sse flask-cors redis gunicorn requests

EXPOSE 8000

CMD ["gunicorn", "-b", "0.0.0.0:8000", "api_gateway:app"]
